# Optimizer
momentum: 0.9
weight_decay: 0.0005
# Epochs
start_epoch: 0
epoch: 120
mile_stone:
  - epoch_start: 0
    epoch_end: 1
    learning_rate: 0.01
  -
    epoch_start: 1
    epoch_end: 70
    learning_rate: 0.1
  -
    epoch_start: 70
    epoch_end: 100
    learning_rate: 0.01
  -
    epoch_start: 100
    epoch_end: 120
    learning_rate: 0.001