# Optimizer
momentum: 0.9
weight_decay: 0.0005
# Epochs
start_epoch: 0
epoch: 5
mile_stone:
  -
    epoch_start: 0
    epoch_end: 1
    learning_rate: 0.1
  -
    epoch_start: 1
    epoch_end: 100
    learning_rate: 0.1
  -
    epoch_start: 100
    epoch_end: 150
    learning_rate: 0.01
  -
    epoch_start: 150
    epoch_end: 180
    learning_rate: 0.001
  -
    epoch_start: 180
    epoch_end: 200
    learning_rate: 0.0001